name: Build VSIX

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YARN_IGNORE_ENGINES: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn package
      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"
